### PR TITLE
Add protocol validations

### PR DESCRIPTION
**Pull request by mpgxvii**
- Add protocol questionnaire name validation. Accepts the following:
```
1. Upper case first letter of words in case of spaces (like Quality Of Life)
2. Underscore separated words like (quality_of_life or QUALITY_OF_LIFE)
```

### CODE REVIEW

**Comment by mpgxvii** [comment]
It's failing for cases like `K_Build_Private` or `THINC-IT`, should we accept these as well?

**Comment by yatharthranjan** [comment]
we can also support `-` as a separator like `quality-of-life`

**Comment by yatharthranjan** [comment]
> It's failing for cases like K_Build_Private or THINC-IT, should we accept these as well?

Yes, these seem fine too

**Comment by mpgxvii** [comment]
> I guess also in the worst case scenario, for a invalid name which can't be reformatted the option to use a specific Kafka topic is still available

Yeah another option would be updating `radar-output`.

**Comment by afolarin** [comment]
(we should document this clearly too)
`kebab-case`, `snake_case` and space-separated `Camel Case` are ok.
but a `non delimited case` may lead to confusion.

**Comment by blootsvoets** [comment]
FYI, legal topic names match regex `[a-zA-Z0-9._-]*`. With the `questionnaire_response` topic I would opt for the same, because the questionnaire ID will be used as a directory name. Special cases
 to disallow: id’s starting with a period `.`. Also indeed I would prefer disallowing spaces, like in the Kafka topics.

**Comment by afolarin** [comment]
I think the suggestion was in addition to the topic rule  `[a-zA-Z0-9._-]*` to add an additional constraint to improve readability on the questionnaire name, as space delimiters would be removed, so as to preserve words in the condensed version.

**Review by afolarin — APPROVED** [review]
LGTM

**Pull request merged**
