### PR TITLE
Modify ESM protocol for STAGING_PROJECT

### PR DESCRIPTION
**Pull request by mpgxvii**
- Use new proposed ESM protocol for CNS sites, testing in `STAGING_PROJECT` project:
6 days, 6 ESMs per day, every 12 weeks
- Increase completion window to 15 minutes from default 10 minutes

### CODE REVIEW

**Comment by yatharthranjan** [comment]
Can we maybe change the interval to every 12 weeks anyway? 
We get a lot of unnecessary notifications every day all the time. If this is just for testing, we can add it as a clinical task too so it's always there?

**Comment by mpgxvii** [comment]
Sure, I can change it to 12 weeks. I was just worried that if we miss the 6 day period, we would have to change the phone's date or enroll with a new subject. Is that fine?

**Comment by mpgxvii** [comment]
> Can we maybe change the interval to every 12 weeks anyway?
> We get a lot of unnecessary notifications every day all the time. If this is just for testing, we can add it as a clinical task too so it's always there?

Made the changes

**Comment by yatharthranjan** [comment]
Can we merge this?

**Pull request merged**
